### ISSUE TITLE
EntityFrameworkCore has AddRange Method

### ISSUE THREAD

**Issue by diev** [TortugaResearch/DotNet-ORM-Cookbook#290]
In ORM Cookbook/Recipes.EntityFrameworkCore/LargeBatch/LargeBatchScenario.cs

              foreach (var employee in employees)
                    context.Employees.Add(employee);

can be replaced with

                context.Employees.AddRange(employees);

as described in <https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addrange>

**Comment by Grauenwolf** [comment]
Thank you for the correction.
